-- Add migration script here
CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  caffeine INTEGER,
  alcohol INTEGER,
  energy INTEGER,
  sugar INTEGER,
  price INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  active BOOLEAN NOT NULL DEFAULT TRUE,
  image INTEGER,
  FOREIGN KEY(image) REFERENCES image(id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  email TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  balance INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  audit BOOLEAN NOT NULL DEFAULT FALSE,
  redirect BOOLEAN NOT NULL DEFAULT TRUE,
  avatar INTEGER,
  FOREIGN KEY(avatar) REFERENCES image(id)
);

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_name TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
