[http]
# Interface and port on which this server will listen.
listen = "0.0.0.0:3000"

[storage]
# connection string to sqlite database.
# Format: sqlite:///path/to/database
database = "sqlite://database.sqlite"
