-- Add migration script here
CREATE TABLE product (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	caffeine INTEGER,
	alcohol INTEGER,
	energy INTEGER,
	sugar INTEGER,
	price INTEGER NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	active BOOLEAN NOT NULL DEFAULT TRUE,
	image INTEGER
);
